@startuml
class Puntaje
class Slayer
class Arma
class Enemigo
class Consumible
class Personaje
class Escopeta
class Pistola
class Bfg
class PlasmaRifle
class Motosierra
class Minigun
class Imp
class HellBaron
class HellKnight
class Aracnotron
class SpiderMasterMind
class IconSin
class CyberDemon
class Boss
class Vida
class Botiquin
class Municion
class Escudo
class Puño
class Pinky
class Revenant
class Llave
class LostSoul
class Archville
Slayer --|> Personaje
Personaje *-- Vida
Enemigo --|> Personaje
Boss --|> Enemigo
Imp --|> Enemigo
Revenant --|> Enemigo
Pinky --|> Enemigo
HellKnight --|> Enemigo
HellBaron --|> Enemigo
Archville --|> Enemigo
LostSoul --|> Enemigo
Aracnotron --|> Enemigo
CyberDemon --|> Boss
SpiderMasterMind --|> Boss
IconSin --|> Boss
Puño --|> Arma
Pistola --|> Arma
Escopeta --|> Arma
Bfg --|> Arma
PlasmaRifle --|> Arma
Motosierra --|> Arma
Minigun --|> Arma
Botiquin --|> Consumible
Municion --|> Consumible
Llave --|> Consumible
Escudo --|> Consumible
Enemigo --|> Puntaje
Consumible --|> Puntaje
Arma --|> Puntaje
Slayer "1" o-- "*" Arma
Slayer "1" o-- "1" Consumible
Slayer o-- Enemigo
Slayer o-- Boss
class Personaje{
- Vida vida
+ Morir()
}
class Arma{
- Disparar()
}
class Consumible{
- Usar()
}
@enduml