@startuml
class Slayer
class Arma
class Enemigo
class Consumible
class Personaje
class Escopeta
class Pistola
class Bfg
class PlasmaRifle
class Motosierra
class Minigun
class Imp
class Hellbaron
class Hellknight
class Aracnotron
class Spidermastermind
class Iconofsin
class Cyberdemon
class Boss
class Vida
class Botiquin
class Municion
class Escudo
class Vida
class Puño
class Pinky
class Revenant
class Llave
class Lostsoul
class Archville
Slayer --> Personaje
Slayer *-- Vida
Slayer o-- Arma
Enemigo --> Personaje
Enemigo *-- Vida
Boss --> Enemigo
Imp --> Enemigo
Revenant --> Enemigo
Pinky --> Enemigo
Hellknight --> Enemigo
Hellbaron --> Enemigo
Archville --> Enemigo
Lostsoul --> Enemigo
Aracnotron --> Enemigo
Cyberdemon --> Boss
Spidermastermind --> Boss
Iconofsin --> Boss
Puño --> Arma
Pistola --> Arma
Escopeta --> Arma
Bfg --> Arma
PlasmaRifle --> Arma
Motosierra --> Arma
Minigun --> Arma
Slayer o-- Consumible
Botiquin --> Consumible
Municion --> Consumible
Llave --> Consumible
Escudo --> Consumible
@enduml